### ISSUE TITLE
Guide for adding fixes and games?

### ISSUE THREAD

**Issue by zarif98** [fgsfds/SteamFD-Fixes-Repo#1]
I would write a guide for people with less than optimal tech experience to allow people to add games to this list! Maybe you can even recommend some XAML GUI editor that the user can use to make changes and upload them here.

**Comment by fgsfds** [comment]
There's already a built-in GUI for adding fixes in Superheater (should be enabled first in the settings). It still needs a tutorial or even a wizard, but it's not too complicated to use.

**Comment by fgsfds** [comment]
Added wiki page https://github.com/fgsfds/Steam-Superheater/wiki/How-to-submit-fixes
