### ISSUE TITLE
Versioning of each of the fixes?

### ISSUE THREAD

**Issue by zarif98** [fgsfds/SteamFD-Fixes-Repo#2]
I am talking specifically about Control's HDR UltraWide RT Patch. Right now the fix mentions v1 but it'd be nice to know what exact version we are running compared to the latest. Right now this patch is on version 1.5: https://community.pcgamingwiki.com/files/file/2581-control-hdrultrawidedlssrt-patch/page/9/?tab=comments#comment-4580

**Comment by fgsfds** [comment]
The actual version is in the description.

![image](https://github.com/fgsfds/SteamFD-Fixes-Repo/assets/4870330/f45bf5fd-f5c3-456e-ac16-59fea1f3cc08)

Versions from xml are for internal use, so the fix can be updated from the app.

**Comment by fgsfds** [comment]
Anyway, from now on I'll put the actual version number in the archive name.
